name: Automated tests
on: push

jobs:
  test_jdk11:
    name: OpenJDK 11 + SonarCloud code analysis
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Otherwise the new code can't be determined or code coverage is less informing
          fetch-depth: 0
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-11-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-11-
      - name: Set JAVA_HOME to OpenJDK 11
        run: echo JAVA_HOME=$JAVA_HOME_11_X64 >> $GITHUB_ENV
      - name: Run Maven Tests with enabled code coverage and upload results to SonarCloud
        run: mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=hexatomic_cff-maven-plugin -Dsonar.organization=hexatomic -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          LANG: en_US.UTF-8